### ISSUE TITLE
One Class Neural Network

### ISSUE THREAD

**Issue by sofiapvcp** [cerlymarco/MEDIUM_NoteBook#31]
Hi, 

I am trying to reproduce your code for the oneclass neural network exactly as it is (but with my own data) but I am facing some issues. Namely, I get the following error message:

"TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.

runfile('C:/Users/SofiaPereira/Documents/Projects/CV/scripts/teste.py', wdir='C:/Users/SofiaPereira/Documents/Projects/CV/scripts')
Found 7 images belonging to 1 classes.
Found 2 images belonging to 2 classes.
WARNING:tensorflow:sample_weight modes were coerced from
  ...
    to  
  ['...']
Train for 0.02734375 steps
Epoch 1/20
1/0 [=========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================] - 1s 735ms/step
Traceback (most recent call last):

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\execute.py", line 61, in quick_execute
    num_outputs)

TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: lambda/Const:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\SofiaPereira\Documents\Projects\CV\scripts\teste.py", line 145, in <module>
    model.fit(wrap_generator(train_generator), steps_per_epoch=train_generator.samples/train_generator.batch_size, epochs=20)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 342, in fit
    total_epochs=epochs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1611, in _filtered_call
    self.captured_inputs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\function.py", line 545, in call
    ctx=ctx)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\eager\execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))

_SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'lambda/Const:0' shape=(3,) dtype=float32>]

I've read somewhere that this has to do with tf2.0's eager execution so I added "tf.compat.v1.disable_eager_execution()" after importing tf. With this, I got the following error: 

Traceback (most recent call last):

  File "C:\Users\SofiaPereira\Documents\Projects\CV\scripts\teste.py", line 144, in <module>
    model = get_model()

  File "C:\Users\SofiaPereira\Documents\Projects\CV\scripts\teste.py", line 92, in get_model
    vgg_16_process = pre_process(GaussianNoise(0.1)(inp))

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 778, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 846, in call
    result = self.function(inputs, **kwargs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\applications\__init__.py", line 46, in wrapper
    return base_fun(*args, **kwargs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\applications\vgg16.py", line 44, in preprocess_input
    return vgg16.preprocess_input(*args, **kwargs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\keras_applications\imagenet_utils.py", line 195, in preprocess_input
    mode=mode, **kwargs)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\keras_applications\imagenet_utils.py", line 151, in _preprocess_symbolic_input
    x = backend.bias_add(x, _IMAGENET_MEAN, data_format)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\backend.py", line 5559, in bias_add
    x = nn.bias_add(x, bias, data_format='NHWC')

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\ops\nn_ops.py", line 2728, in bias_add
    with ops.name_scope(name, "BiasAdd", [value, bias]) as name:

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6237, in __enter__
    g_from_inputs = _get_graph_from_inputs(self._values)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5883, in _get_graph_from_inputs
    _assert_same_graph(original_graph_element, graph_element)

  File "C:\Users\SofiaPereira\anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py", line 5818, in _assert_same_graph
    (item, original_item))

ValueError: Tensor("lambda/Const:0", shape=(3,), dtype=float32) must be from the same graph as Tensor("lambda_9/strided_slice:0", shape=(None, 224, 224, 3), dtype=float32).

Do you have any idea regarding what's going on? I am using an Anaconda Env with tf=2.0

Thank you very much,
Sofia

**Comment by cerlymarco** [comment]
just tested the same code on a simply dummy dataset...

This error doesn't appear: https://colab.research.google.com/drive/1FcuJTFC9m8A2JJj7Ge3kiJVpbhFpa8f5?usp=sharing

Maybe u made some wrong manipulation to the network or u use an old tf/keras version

it's difficult to say more

**Comment by sofiapvcp** [comment]
Hi, as I mentioned upon raising the issue, I am using tf 2.0, which I would not consider to be an old tf version. 
By downgrading colab's tf to 2.0 I am able to reproduce the issue I was facing in my Anaconda env (with a slightly different error message than the one I mentioned above but which is the same one I am getting at the moment using my pc): [https://colab.research.google.com/drive/1FcuJTFC9m8A2JJj7Ge3kiJVpbhFpa8f5?usp=sharing](url). 

Therefore, I am going to assume it is a version-related problem. Sharing the environments you used for building each notebook might help to avoid similar issues in the future. Anyways, your colab notebook was extremely helpful and ultimately made me realize what was happening.

Cheers! 
Sofia
